-- init-db/seed.sql
-- Idempotente: ON CONFLICT DO NOTHING garante segurança em re-execuções

INSERT INTO eventos (id, nome_evento, personalizavel, horario) VALUES
    (gen_random_uuid(), 'temperatura alta',  true, NOW()),
    (gen_random_uuid(), 'temperatura baixa', true, NOW()),
    (gen_random_uuid(), 'umidade baixa',     true, NOW()),
    (gen_random_uuid(), 'vento',             true, NOW()),
    (gen_random_uuid(), 'chuva',             true, NOW())
ON CONFLICT (nome_evento) DO NOTHING;

-- Cidades: municípios de Goiás (espelhado de modulo_usuarios)
INSERT INTO cidades (id, nome) VALUES
    (gen_random_uuid(), 'Abadia de Goiás'),
    (gen_random_uuid(), 'Abadiânia'),
    (gen_random_uuid(), 'Acreúna'),
    (gen_random_uuid(), 'Adelândia'),
    (gen_random_uuid(), 'Água Fria de Goiás'),
    (gen_random_uuid(), 'Água Limpa'),
    (gen_random_uuid(), 'Águas Lindas de Goiás'),
    (gen_random_uuid(), 'Alexânia'),
    (gen_random_uuid(), 'Aloândia'),
    (gen_random_uuid(), 'Alto Horizonte'),
    (gen_random_uuid(), 'Alto Paraíso de Goiás'),
    (gen_random_uuid(), 'Alvorada do Norte'),
    (gen_random_uuid(), 'Amaralina'),
    (gen_random_uuid(), 'Americano do Brasil'),
    (gen_random_uuid(), 'Amorinópolis'),
    (gen_random_uuid(), 'Anápolis'),
    (gen_random_uuid(), 'Anhanguera'),
    (gen_random_uuid(), 'Anicuns'),
    (gen_random_uuid(), 'Aparecida de Goiânia'),
    (gen_random_uuid(), 'Aparecida do Rio Doce'),
    (gen_random_uuid(), 'Apore'),
    (gen_random_uuid(), 'Araçu'),
    (gen_random_uuid(), 'Aragarças'),
    (gen_random_uuid(), 'Aragoiânia'),
    (gen_random_uuid(), 'Araguapaz'),
    (gen_random_uuid(), 'Arenópolis'),
    (gen_random_uuid(), 'Aruanã'),
    (gen_random_uuid(), 'Aurilândia'),
    (gen_random_uuid(), 'Avelinópolis'),
    (gen_random_uuid(), 'Baliza'),
    (gen_random_uuid(), 'Barro Alto'),
    (gen_random_uuid(), 'Bela Vista de Goiás'),
    (gen_random_uuid(), 'Bom Jardim de Goiás'),
    (gen_random_uuid(), 'Bom Jesus de Goiás'),
    (gen_random_uuid(), 'Bonfinópolis'),
    (gen_random_uuid(), 'Bonópolis'),
    (gen_random_uuid(), 'Brazabrantes'),
    (gen_random_uuid(), 'Britânia'),
    (gen_random_uuid(), 'Buriti Alegre'),
    (gen_random_uuid(), 'Buriti de Goiás'),
    (gen_random_uuid(), 'Buritinópolis'),
    (gen_random_uuid(), 'Cabeceiras'),
    (gen_random_uuid(), 'Cachoeira Alta'),
    (gen_random_uuid(), 'Cachoeira de Goiás'),
    (gen_random_uuid(), 'Cachoeira Dourada'),
    (gen_random_uuid(), 'Caçu'),
    (gen_random_uuid(), 'Caiapônia'),
    (gen_random_uuid(), 'Caldas Novas'),
    (gen_random_uuid(), 'Caldazinha'),
    (gen_random_uuid(), 'Campestre de Goiás'),
    (gen_random_uuid(), 'Campinaçu'),
    (gen_random_uuid(), 'Campinorte'),
    (gen_random_uuid(), 'Campo Alegre de Goiás'),
    (gen_random_uuid(), 'Campo Limpo de Goiás'),
    (gen_random_uuid(), 'Campos Belos'),
    (gen_random_uuid(), 'Campos Verdes'),
    (gen_random_uuid(), 'Carmo do Rio Verde'),
    (gen_random_uuid(), 'Castelândia'),
    (gen_random_uuid(), 'Catalão'),
    (gen_random_uuid(), 'Caturaí'),
    (gen_random_uuid(), 'Cavalcante'),
    (gen_random_uuid(), 'Ceres'),
    (gen_random_uuid(), 'Cezarina'),
    (gen_random_uuid(), 'Chapadão do Céu'),
    (gen_random_uuid(), 'Cidade Ocidental'),
    (gen_random_uuid(), 'Cocalzinho de Goiás'),
    (gen_random_uuid(), 'Colinas do Sul'),
    (gen_random_uuid(), 'Córrego do Ouro'),
    (gen_random_uuid(), 'Corumbá de Goiás'),
    (gen_random_uuid(), 'Corumbaíba'),
    (gen_random_uuid(), 'Cristalina'),
    (gen_random_uuid(), 'Cristianópolis'),
    (gen_random_uuid(), 'Crixás'),
    (gen_random_uuid(), 'Cromínia'),
    (gen_random_uuid(), 'Cumari'),
    (gen_random_uuid(), 'Damianópolis'),
    (gen_random_uuid(), 'Damolândia'),
    (gen_random_uuid(), 'Davinópolis'),
    (gen_random_uuid(), 'Diorama'),
    (gen_random_uuid(), 'Divinópolis de Goiás'),
    (gen_random_uuid(), 'Doverlândia'),
    (gen_random_uuid(), 'Edealina'),
    (gen_random_uuid(), 'Edéia'),
    (gen_random_uuid(), 'Estrela do Norte'),
    (gen_random_uuid(), 'Faina'),
    (gen_random_uuid(), 'Fazenda Nova'),
    (gen_random_uuid(), 'Firminópolis'),
    (gen_random_uuid(), 'Flores de Goiás'),
    (gen_random_uuid(), 'Formosa'),
    (gen_random_uuid(), 'Formoso'),
    (gen_random_uuid(), 'Gameleira de Goiás'),
    (gen_random_uuid(), 'Goianápolis'),
    (gen_random_uuid(), 'Goiandira'),
    (gen_random_uuid(), 'Goianésia'),
    (gen_random_uuid(), 'Goiânia'),
    (gen_random_uuid(), 'Goianira'),
    (gen_random_uuid(), 'Goiás'),
    (gen_random_uuid(), 'Goiatuba'),
    (gen_random_uuid(), 'Gouvelândia'),
    (gen_random_uuid(), 'Guapó'),
    (gen_random_uuid(), 'Guaraíta'),
    (gen_random_uuid(), 'Guarani de Goiás'),
    (gen_random_uuid(), 'Guarinos'),
    (gen_random_uuid(), 'Heitoraí'),
    (gen_random_uuid(), 'Hidrolândia'),
    (gen_random_uuid(), 'Hidrolina'),
    (gen_random_uuid(), 'Iaciara'),
    (gen_random_uuid(), 'Inaciolândia'),
    (gen_random_uuid(), 'Indiara'),
    (gen_random_uuid(), 'Inhumas'),
    (gen_random_uuid(), 'Ipameri'),
    (gen_random_uuid(), 'Ipiranga de Goiás'),
    (gen_random_uuid(), 'Iporá'),
    (gen_random_uuid(), 'Israelândia'),
    (gen_random_uuid(), 'Itaberaí'),
    (gen_random_uuid(), 'Itaguari'),
    (gen_random_uuid(), 'Itaguaru'),
    (gen_random_uuid(), 'Itajá'),
    (gen_random_uuid(), 'Itapaci'),
    (gen_random_uuid(), 'Itapirapuã'),
    (gen_random_uuid(), 'Itapuranga'),
    (gen_random_uuid(), 'Itarumã'),
    (gen_random_uuid(), 'Itauçu'),
    (gen_random_uuid(), 'Itumbiara'),
    (gen_random_uuid(), 'Ivolândia'),
    (gen_random_uuid(), 'Jandaia'),
    (gen_random_uuid(), 'Jaraguá'),
    (gen_random_uuid(), 'Jataí'),
    (gen_random_uuid(), 'Jaupaci'),
    (gen_random_uuid(), 'Jesúpolis'),
    (gen_random_uuid(), 'Joviânia'),
    (gen_random_uuid(), 'Jussara'),
    (gen_random_uuid(), 'Lagoa Santa'),
    (gen_random_uuid(), 'Leopoldo de Bulhões'),
    (gen_random_uuid(), 'Luziânia'),
    (gen_random_uuid(), 'Mairipotaba'),
    (gen_random_uuid(), 'Mambaí'),
    (gen_random_uuid(), 'Mara Rosa'),
    (gen_random_uuid(), 'Marzagão'),
    (gen_random_uuid(), 'Matrinchã'),
    (gen_random_uuid(), 'Maurilândia'),
    (gen_random_uuid(), 'Mimoso de Goiás'),
    (gen_random_uuid(), 'Minaçu'),
    (gen_random_uuid(), 'Mineiros'),
    (gen_random_uuid(), 'Moiçorá'),
    (gen_random_uuid(), 'Monte Alegre de Goiás'),
    (gen_random_uuid(), 'Montes Claros de Goiás'),
    (gen_random_uuid(), 'Montividiu'),
    (gen_random_uuid(), 'Montividiu do Norte'),
    (gen_random_uuid(), 'Morrinhos'),
    (gen_random_uuid(), 'Morro Agudo de Goiás'),
    (gen_random_uuid(), 'Mossâmedes'),
    (gen_random_uuid(), 'Mozarlândia'),
    (gen_random_uuid(), 'Mundo Novo'),
    (gen_random_uuid(), 'Mutunópolis'),
    (gen_random_uuid(), 'Nazário'),
    (gen_random_uuid(), 'Nerópolis'),
    (gen_random_uuid(), 'Niquelândia'),
    (gen_random_uuid(), 'Nova América'),
    (gen_random_uuid(), 'Nova Aurora'),
    (gen_random_uuid(), 'Nova Crixás'),
    (gen_random_uuid(), 'Nova Glória'),
    (gen_random_uuid(), 'Nova Iguaçu de Goiás'),
    (gen_random_uuid(), 'Nova Roma'),
    (gen_random_uuid(), 'Nova Veneza'),
    (gen_random_uuid(), 'Novo Brasil'),
    (gen_random_uuid(), 'Novo Gama'),
    (gen_random_uuid(), 'Novo Planalto'),
    (gen_random_uuid(), 'Orizona'),
    (gen_random_uuid(), 'Ouro Verde de Goiás'),
    (gen_random_uuid(), 'Ouvidor'),
    (gen_random_uuid(), 'Padre Bernardo'),
    (gen_random_uuid(), 'Palestina de Goiás'),
    (gen_random_uuid(), 'Palmeiras de Goiás'),
    (gen_random_uuid(), 'Palmelo'),
    (gen_random_uuid(), 'Palminópolis'),
    (gen_random_uuid(), 'Panamá'),
    (gen_random_uuid(), 'Paranaiguara'),
    (gen_random_uuid(), 'Paraúna'),
    (gen_random_uuid(), 'Perolândia'),
    (gen_random_uuid(), 'Petrolina de Goiás'),
    (gen_random_uuid(), 'Pilar de Goiás'),
    (gen_random_uuid(), 'Piracanjuba'),
    (gen_random_uuid(), 'Piranhas'),
    (gen_random_uuid(), 'Pirenópolis'),
    (gen_random_uuid(), 'Pires do Rio'),
    (gen_random_uuid(), 'Planaltina'),
    (gen_random_uuid(), 'Pontalina'),
    (gen_random_uuid(), 'Porangatu'),
    (gen_random_uuid(), 'Porteirão'),
    (gen_random_uuid(), 'Portelândia'),
    (gen_random_uuid(), 'Posse'),
    (gen_random_uuid(), 'Professor Jamil'),
    (gen_random_uuid(), 'Quirinópolis'),
    (gen_random_uuid(), 'Região Metropolitana de Goiânia'),
    (gen_random_uuid(), 'Rialma'),
    (gen_random_uuid(), 'Rianápolis'),
    (gen_random_uuid(), 'Rio Quente'),
    (gen_random_uuid(), 'Rio Verde'),
    (gen_random_uuid(), 'Rio Verde Região Leste'),
    (gen_random_uuid(), 'Rio Verde Região Norte'),
    (gen_random_uuid(), 'Rio Verde Região Sul'),
    (gen_random_uuid(), 'Rubiataba'),
    (gen_random_uuid(), 'Sanclerlândia'),
    (gen_random_uuid(), 'Santa Bárbara de Goiás'),
    (gen_random_uuid(), 'Santa Cruz de Goiás'),
    (gen_random_uuid(), 'Santa Fé de Goiás'),
    (gen_random_uuid(), 'Santa Helena de Goiás'),
    (gen_random_uuid(), 'Santa Isabel'),
    (gen_random_uuid(), 'Santa Rita do Araguaia'),
    (gen_random_uuid(), 'Santa Rita do Novo Destino'),
    (gen_random_uuid(), 'Santa Rosa de Goiás'),
    (gen_random_uuid(), 'Santa Tereza de Goiás'),
    (gen_random_uuid(), 'Santa Terezinha de Goiás'),
    (gen_random_uuid(), 'Santo Antônio da Barra'),
    (gen_random_uuid(), 'Santo Antônio de Goiás'),
    (gen_random_uuid(), 'Santo Antônio do Descoberto'),
    (gen_random_uuid(), 'São Domingos'),
    (gen_random_uuid(), 'São Francisco de Goiás'),
    (gen_random_uuid(), 'São João d''Aliança'),
    (gen_random_uuid(), 'São João da Paraúna'),
    (gen_random_uuid(), 'São Luís de Montes Belos'),
    (gen_random_uuid(), 'São Luiz do Norte'),
    (gen_random_uuid(), 'São Miguel do Araguaia'),
    (gen_random_uuid(), 'São Miguel do Passa Quatro'),
    (gen_random_uuid(), 'São Patrício'),
    (gen_random_uuid(), 'São Simão'),
    (gen_random_uuid(), 'Senador Canedo'),
    (gen_random_uuid(), 'Serranópolis'),
    (gen_random_uuid(), 'Silvânia'),
    (gen_random_uuid(), 'Simolândia'),
    (gen_random_uuid(), 'Sítio d''Abadia'),
    (gen_random_uuid(), 'Taquaral de Goiás'),
    (gen_random_uuid(), 'Teresina de Goiás'),
    (gen_random_uuid(), 'Terezópolis de Goiás'),
    (gen_random_uuid(), 'Três Ranchos'),
    (gen_random_uuid(), 'Trindade'),
    (gen_random_uuid(), 'Trombas'),
    (gen_random_uuid(), 'Turvânia'),
    (gen_random_uuid(), 'Turvelândia'),
    (gen_random_uuid(), 'Uirapuru'),
    (gen_random_uuid(), 'Uruaçu'),
    (gen_random_uuid(), 'Urutaí'),
    (gen_random_uuid(), 'Valparaíso de Goiás'),
    (gen_random_uuid(), 'Várjão'),
    (gen_random_uuid(), 'Vianópolis'),
    (gen_random_uuid(), 'Vicentinópolis'),
    (gen_random_uuid(), 'Vila Boa'),
    (gen_random_uuid(), 'Vila Propício')
ON CONFLICT (nome) DO NOTHING;